# Generated by Django 5.2.1 on 2026-04-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idempotencykey',
            name='request_hash',
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='ledger_amount_positive'),
        ),
    ]
